//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharp_wpf_exercise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class highest_product_v
    {
        public Nullable<decimal> Price { get; set; }
        public string Name { get; set; }
    }
}
